config/routes.rb
Hera::Application.routes.draw do
 
  devise_for :users, controllers: {users: "users"}
  
  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end
  
  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  
  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  resources :inspections
  
  resources :groups
  
  resources :buildings
  
  resources :user
  
  resources :equip_types
  
  get "gerenciamento/index"
  

  root 'gerenciamento#index'

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :inspections
	belongs_to :equip_type
	belongs_to :building
  
	validates :is_there, :inclusion => {:in => [true, false]}
  
  
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_filter :authenticate_user!

  def show
      @equipment = Equipment.find params[:id]
      if (@equipment.nil?)
        redirect_to equipment_index_path
      else
        @inspection = @equipment.inspections.last
        if (@inspection.nil?)
          redirect_to equipment_index_path
        else
          @answers = @inspection.answers
        end
      end
  end
  
  def new
    @equipment = Equipment.new
    @predios = Building.all.collect{|p| [p.name,p.id]}
    @predio = 0
    @tipos = EquipType.all.collect{|p| [p.kind,p.id]}
    @tipo = 0
    @simnao = [["Existe",true],["Não Existe",false]]
    @existe = true
  end
  
  def create
    equipment = Equipment.new
    equipment.update_attributes(equipment_params)
    equipment.save
    redirect_to equipment_index_path
  end
  
  def edit
    @equipment = Equipment.find_or_create_by_id(params[:id])
    @predios = Building.all.collect{|p| [p.name,p.id]}
    @predio = @equipment.building.id
    @tipos = EquipType.all.collect{|p| [p.kind,p.id]}
    @tipo = 0
    @simnao = [["Existe",true],["Não Existe",false]]
    @existe = @equipment.is_there
  end
  
  def update
    equipment = Equipment.find params[:id]
    equipment.update_attributes(equipment_params)
    equipment.save
    redirect_to equipment_index_path
  end

  def validate
    @inspection = Inspection.find(params[:id])
    @inspection.update_column :approved, 1
    redirect_to action: :show, id: @inspection.id
  end

  def disapprove
    @inspection = Inspection.find(params[:id])
    @inspection.update_column :approved, 2
    redirect_to action: :show, id: @inspection.id
  end

  def index
    respond_to do |format|
      format.html {
        @inspections = Inspection.all

        @equipments = Equipment.all
        @equipments = @equipments.where("equip_type_id = ?", params[:etype]) unless params[:etype].blank?
        @equipments = @equipments.where(building_id: params[:building_id]) unless params[:building_id].blank?
        @equipments = @equipments.where(%q{equipment.id in (
                      select B.EquipmentID from (
                        select T.EquipmentID, T.is_ok from (
                          select inspections.equipment_id as EquipmentID, answers.is_ok as is_ok from equipment
                          join inspections on equipment.id=inspections.equipment_id
                          join answers on answers.inspection_id=inspections.id
                          join checklist_items on checklist_items.id=answers.checklist_item_id
                          where question like 'O equipamento est% conservado%'
                          order by inspections.id desc) as T
                        group by EquipmentID) as B where B.is_ok = ?)}, params[:conserved_id]) unless params[:conserved_id].blank?


        @equipTypes = EquipType.order("kind").all
        @users = User.all
        @buildings = Building.order("name").all
      }

      format.json {
        if params[:building_id]
          @equipment = Equipment.where(building_id: params[:building_id])
        else
          @equipment = Equipment.all
        end
      }

    end
  end
  
  def equipment_params
    params.require(:equipment).permit(:name,:is_there,:equip_type_id,:building_id,:floor,:id_place)
  end


end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_search.html.erb
<div class="container">
  <%= form_tag(equipment_index_path, method: "get") do %>
  <p>
  Predio:
    <%= building_array = @buildings.map {|building| [building.name, building.id]}
    building_array.unshift(['',''])
    select_tag(:building_id, options_for_select(building_array)) %>

  Equipamento:
    <% equip_type_array = @equipTypes.map {|etype| [etype.kind, etype.id]}
    equip_type_array.unshift(['',''])%>
    <%= select_tag(:etype, options_for_select(equip_type_array)) %>

  Estado de Conservação
    <%= select_tag(:conserved_id, options_for_select([['',''], ['Conservado', 0], ['Não Conservado', 1]])) %>


    <%= submit_tag("Aplicar Filtros")%>
    <% end %>
  </p>


</div>

app/views/equipment/_showInspection.erb
<table class="table">    
    <tr>
        <th>ID</th>
        <td><%= @inspection.id%></td>
    </tr>
    <tr>
        <th>Grupo</th>
        <td><%= @inspection.group.try(:name)%></td>
    </tr>
    <tr>
        <th>Tipo de Equipamento</th>
        <td><%= @inspection.equipment.equip_type.kind%></td>
    </tr>
    <tr>
        <th>Localização</th>
        <td><%= @inspection.equipment.building.name%></td>
    </tr>
    <tr>
        <th>Data da Inspeção</th>
        <td><%= @inspection.created_at%></td>
    </tr>
    <tr>
        <th>Inspetor</th>
        <td><%= @inspection.user.name%></td>
    </tr>
    <tr>
        <th>Descrição</th>
        <td><%= @inspection.description%></td>
    </tr>
    <tr>
        <th>Aprovado?</th>
        <td> <% if (@inspection.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (@inspection.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (@inspection.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                if (@inspection.approved == 3)
                    %><p class="text-muted">Enviado</p><%
                end
                %></td>
    </tr>
</table>

<h3>Checklist</h3>

<% if (@inspection.equipment.is_there)  %>
<table class="table">
    <% @answers.each do |answer| %>
        <tr>
            <td>
                <% if !answer.checklist_item.nil? %>
                  <%= answer.checklist_item.question %>
                <%  else %>
                  !PERGUNTA REMOVIDA!
                <% end %>
            </td>
            <td>
                <% if (answer.is_ok == 0)
                        %><p class="text-muted">Sim</p><% end
                    if (answer.is_ok == 1)
                        %><p class="text-muted">Não</p><% end
                    if (answer.is_ok == 2)
                        %><p class="text-muted">Não se aplica</p><%
                    end
                %>
            </td>
        </tr>
    <% end else %>
    <tr>Equipamento não existe</tr>
    <% end %>
</table>

<div class="container">
  <table>
    <tr>
        <% if (@inspection.approved == 0) then %>
       <td>
            <%= link_to 'Aprovar', { action: :validate, id: @inspection.id },  method: :validate,  :onclick => "return confirm('Certeza que deseja aprovar a inspeção?')", class: "btn btn-success"%></td>
      <td><%= link_to 'Reprovar', { action: :disapprove, id: @inspection.id },  method: :disapprove,  :onclick => "return confirm('Certeza que deseja reprovar a inspeção?')", class: "btn btn-danger" %></td>
      <% end %>

    </tr>
  </table>
</div>

app/views/equipment/disapprove.html.erb
<h1>Equipment#disapprove</h1>
<p>Find me in app/views/equipment/disapprove.html.erb</p>

app/views/equipment/edit.html.erb
<%= nested_form_for @equipment do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :id_place, "ID do Local" %>
  <%= f.text_field :id_place %>

  <%= f.label :floor, "Pavimento" %>
  <%= f.text_field :floor %>

  <%= f.label :equip_type_id, "Tipo do Ítem" %>
  <%= f.select(:equip_type_id, options_for_select(@tipos, @tipo)) %>

  <%= f.label :building_id, "Localização" %>
  <%= f.select(:building_id, options_for_select(@predios, @predio)) %>

  <%= f.label :is_there, "Existe" %>
  <%= f.select(:is_there, options_for_select(@simnao, @existe)) %> 
  <br/>
  <%= f.submit "Salvar" %>
  
<%end%>

app/views/equipment/index.html.erb
<div class="search">
  <%= render :partial => 'search' %>
</div>


<td><i><%= link_to "Adicionar novo ítem", new_equipment_path %></i>
<table class="table table-striped table-hover">
    <tr>
        <th></th>
        <th>Nome</th>
        <th>Tipo do Ítem</th>
        <th>Localização</th>
        <th>Andar</th>
        <th>Existe</th>
        <th>Estado de Conservação</th>
        <th></th>
        <th></th>
    </tr>
    <% @equipments.each do |equipment| %>
        <tr>
            <td>
               <%= equipment.id %>
            </td>
            <td>
                <%= equipment.name %>
            </td>
            <td>
                <%= equipment.equip_type.try(:kind) %>
            </td>
            <td>
               <%= equipment.building.name %>
            </td>
            <td>
                <%= equipment.floor %>
            </td>
            <td>
                <% if (equipment.is_there)
                    %>Sim<%
                else (equipment.is_there)
                    %>Não<%
                end
                %>
            </td>

              <% if (!equipment.inspections.empty?) %>
                <!-- Ha inspecoes -->
                <% if (!equipment.inspections.last.answers.empty?) %>
                <td> <% if (equipment.inspections.last.answers.first.is_ok == 0)
                  %><p class="text-muted">Conservado</p><% end
                  if (equipment.inspections.last.answers.first.is_ok == 1)
                  %><p class="text-muted">Não Conservado</p><% end
                  if (equipment.inspections.last.answers.first.is_ok == 2)
                  %><p class="text-muted">Não se aplica</p><% end
                %></td>
    
                <td>
                  <%= link_to "Visualizar", equipment_path(equipment)  %>
                </td>
                <% else %>
                  <td> Não há inspeções</td>
                  <td>Sem Visualização</td>
                <%end%>
              <% else %>
                <!-- Nao ha inspecoes -->
                <td> Não há inspeções</td>
                <td>Sem Visualização</td>
              <%end%>
                
            <td><%= link_to "Editar", edit_equipment_path(:id => equipment.id) %>
        </tr>
    <% end -%>
</table>
<!--button_to "Adicionar equipamento", new_equipment_path, :method => "get" -->

app/views/equipment/new.html.erb
<%= nested_form_for @equipment do |f| %>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name %>

  <%= f.label :id_place, "ID do Local" %>
  <%= f.text_field :id_place %>

  <%= f.label :floor, "Pavimento" %>
  <%= f.text_field :floor %>

  <%= f.label :equip_type_id, "Tipo do Ítem" %>
  <%= f.select(:equip_type_id, options_for_select(@tipos, @tipo)) %>

  <%= f.label :building_id, "Localização" %>
  <%= f.select(:building_id, options_for_select(@predios, @predio)) %>

  <%= f.label :is_there, "Existe" %>
  <%= f.select(:is_there, options_for_select(@simnao, @existe)) %> 
  <br/>
  <%= f.submit "Criar" %>
  
<%end%>

app/views/equipment/show.html.erb
<h2>Visualização de Equipamento</h2>


<table class="table">
    <tr>
        <th>ID</th>
        <td><%= @equipment.id%></td>
    </tr>

     <tr>
        <th>Nome</th>
        <td><%= @equipment.name%></td>
    </tr>
    <tr>
        <th>Tipo</th>
        <td><%= @equipment.equip_type.kind %></td>
    </tr>
    <tr>
        <th>Localização</th>
        <td><%= @equipment.building.name %></td>
    </tr>
     <tr>
        <th>Andar</th>
        <td><%= @equipment.floor%></td>
    </tr>
     <tr>
        <th>ID do Local no Atlas</th>
        <td><%= @equipment.id_place%></td>
    </tr>
    <tr>
        <th>Existe</th>
        <td>
            <% if (@equipment.is_there)
                    %>Sim<%
                else %>Não<%
                end
            %>

        <td>
    </tr>
</table>



<h3>Última Inspeção</h3>

<%= render :partial => 'showInspection' %>

<table>
    <tr>
      <td><%= link_to "Ver inspecoes anteriores", inspections_index_history_path(:equipment_id => @equipment.id), class: "btn btn-default", method: "get"%></td>
    </tr>
  </table>
</div>

<br>
<div class="container">
<img src="<%= @inspection.photo_url%>" class="img-rounded">
</div>

app/views/equipment/validate.html.erb
<h1>Equipment#validate</h1>
<p>Find me in app/views/equipment/validate.html.erb</p>