config/routes.rb
Hera::Application.routes.draw do
 
  devise_for :users, controllers: {users: "users"}
  
  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end
  
  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  
  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  resources :inspections
  
  resources :groups
  
  resources :buildings
  
  resources :user
  
  resources :equip_types
  
  get "gerenciamento/index"
  

  root 'gerenciamento#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	self.inheritance_column = nil
	has_many :inspections

	validates :nusp, uniqueness: true
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    @inspections = Inspection.all
    @equipTypes = EquipType.all
    @users = User.all
    @users = @users.where("name like ?", "%#{params[:search]}%") unless params[:search].blank?
    @users = @users.where("kind = ?", params[:user_type]) unless params[:user_type].blank?
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find params[:id]
    @roles = [["Administrador/Aprovador","admin"],["Normal","normal"]]
    @role = @user.kind
    
    if (@role.nil?) 
      @role = "normal"
    end
  end
  
  def update
    user = User.find params[:id]
    user.update_attributes(userdata_params)
    user.save
    redirect_to user_path(params[:id])
  end
  
  def userdata_params
    params.require(:user).permit(:name,:nusp,:cpf,:kind)
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_search.html.erb
<div class="container">

  <%= form_tag(user_index_path, method: "get") do %>

  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

  <%= form_tag(user_index_path, method: "get") do %>
  <p> Tipo:
    <%= select_tag(:user_type, options_for_select([['',0], ['Administrador', 'admin'], ['Estagiário', 'estag']])) %>
  </p>


    <%= submit_tag("Aplicar Filtros")%>
    <% end %>

</div>

app/views/user/edit.html.erb
<%= nested_form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :nusp, "Número USP" %>
  <%= f.text_field :nusp %>

  <%= f.label :cpf, "CPF" %>
  <%= f.text_field :cpf %>

  <% if current_user.kind == "admin" %>
    <%= f.label :kind, "Tipo de Usuário" %>
    <%= f.select(:kind, options_for_select(@roles, @role)) %>
  
  <%  end %>

  <br/>
  <%= f.submit "Salvar" %>
<%  end %>

app/views/user/index.html.erb
<div class="search">
  <%= render :partial => 'search' %>
</div>


<table class="table table-striped table-hover">
    <tr>
        <th></th>
        <th>Nome</th>
        <th>CPF</th>
        <th>Número USP</th>
        <th>Tipo</th>
        <th>E-mail</th>
        <th></th>
        <th></th>
    </tr>

    <% @users.each do |user| %>
        <tr>
            <td>
               <%= user.id %>
            </td>
            <td>
                <%= user.name %>
            </td>
            <td>
               <%= user.cpf %>
            </td>
            <td>
               <%= user.nusp %>
            </td>
            <td>
                <%= user.kind %>
            </td>
            <td>
                <%= user.email%>
            </td>
            <td>
                    <%= link_to "Visualizar", user_path(:id => user.id)  %>

            </td>
            <td>
              <%= link_to "Editar Dados", edit_user_path(:id => user.id)  %>
           </td>
        </tr>
    <% end -%>
</table>

app/views/user/show.html.erb
<h2>Visualização de Usuário</h2>


<table class="table">
    <tr>
        <th>ID</th>
        <td><%= @user.id%></td>
    </tr>
    <tr>
        <th>Nome</th>
        <td><%= @user.name %></td>
    </tr>
    <tr>
        <th>CPF</th>
        <td><%= @user.cpf %></td>
    </tr>
    <tr>
        <th>Número USP</th>
        <td><%= @user.nusp %></td>
    </tr>
    <tr>
        <th>Tipo</th>
        <td><%= @user.kind %></td>
    </tr>
    <tr>
        <th>E-mail</th>
        <td><%= @user.email %></td>
    </tr>
</table>