config/routes.rb
Hera::Application.routes.draw do
 
  devise_for :users, controllers: {users: "users"}
  
  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end
  
  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  
  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  resources :inspections
  
  resources :groups
  
  resources :buildings
  
  resources :user
  
  resources :equip_types
  
  get "gerenciamento/index"
  

  root 'gerenciamento#index'

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :group
	belongs_to :user
	belongs_to :equipment
	has_many :answers

	mount_uploader :photo_url, PictureUploader
end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
	before_filter :authenticate_user!

	def show
		@inspection = Inspection.find(params[:id]);
		@answers = Answer.where(inspection_id: params[:id])
    prepared_url = @inspection.photo_url.to_s
    prepared_url.slice!(0)    
    @inspection_url = root_url + prepared_url
	end

	def validate
    if (current_user.kind == "admin")
      @inspection = Inspection.find(params[:id])
      @inspection.update_column :approved, 1
      redirect_to action: :show, id: @inspection.id
    else
      redirect_to action: :show, id: @inspection.id
    end
	end

	def disapprove
    if (current_user.kind == "admin")
      @inspection = Inspection.find(params[:id])
      @inspection.update_column :approved, 2
      redirect_to action: :show, id: @inspection.id
    else
      redirect_to action: :show, id: @inspection.id
    end    
	end
  
  def new
    @inspection = Inspection.new
    @equipments = Equipment.all.collect{|p| [p.name,p.id]}
    @equipment = 0
  end
  
  def create
    inspection = Inspection.new
    inspection.update_attributes(inspection_params)
    inspection.save
    redirect_to edit_inspection_path(inspection.id)
  end
  
  def edit
    @inspection = Inspection.find(params[:id])
    @questions = @inspection.equipment.equip_type.checklist_items.collect{|p| [p.id, p.question] }
    @answertypes = [["Sim",0],["Não",1], ["Não se Aplica",2]]
    
    @answer_data = Answer.where(inspection_id: params[:id])
    
    @answer_test = @answer_data.where(checklist_item_id: 29)
    

  end
  
  def update
    inspection = Inspection.find params[:id]
    inspection.group_id = params[:inspection][:group_id]
    inspection.save
    answer_data = params[:answers]
    answer_data.each do |answer|
      answer_db = Answer.where(inspection_id: inspection.id, checklist_item_id: answer[0])
      answer_db_data = answer_db.first #passa de relation para o objeto que precisamos
      
      photo_data = nil
      
      if (!params[:photos].nil?)
        photo_data = params[:photos][answer[0]]
      end
      
      if (answer_db_data.nil?)
        answer_new = Answer.new
        answer_new.inspection_id = inspection.id
        answer_new.checklist_item_id = answer[0]
        answer_new.is_ok = answer[1]
        answer_new.comment = params["comment_" + answer[0].to_s]
        answer_new.save
        
        #upload!
        if (!photo_data.nil?)
          photo_data.each do |photo|
            new_upload = Upload.new
            new_upload.answer_id = answer_new.id
            new_upload.photo = photo
            new_upload.save
          end
        end
      else
        answer_db_data.is_ok = answer[1]
        answer_db_data.comment = params["comment_" + answer[0].to_s]
        answer_db_data.save
        
        #upload!
        if (!photo_data.nil?)
          photo_data.each do |photo|
            new_upload = Upload.new
            new_upload.answer_id = answer_db_data.id
            new_upload.photo = photo
            new_upload.save
          end
        end
      end
    end
    redirect_to inspection_path id: inspection.id
  end

	def index
		@equip_types = EquipType.order("kind").all
		@users = User.order("name").where(kind: "estag")
		@buildings = Building.order("name").all

		@inspections = Inspection.where(approved: 0).order("created_at DESC")
		@inspections = @inspections.where("user_id = ?", params[:user_id]) unless params[:user_id].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {equip_type_id: params[:equip_type_id]}) unless params[:equip_type_id].blank?
		@inspections = @inspections.where("inspections.created_at > ?", params[:data1]) unless params[:data1].blank?
		@inspections = @inspections.where("inspections.created_at < ?", params[:data2]) unless params[:data2].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {building_id: params[:building_id]}) unless params[:building_id].blank?
		@inspections = @inspections.where(equipment_id: params[:equipment_id]) unless params[:equipment_id].blank?
	end

	def index_history
		@equip_types = EquipType.order("kind").all
		@users = User.order("name").where(kind: "estag")
		@buildings = Building.order("name").all

		@inspections = Inspection.where("approved <> 0").order("created_at DESC")
		@inspections = @inspections.where("user_id = ?", params[:user_id]) unless params[:user_id].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {equip_type_id: params[:equip_type_id]}) unless params[:equip_type_id].blank?
		@inspections = @inspections.where("inspections.created_at > ?", params[:data1]) unless params[:data1].blank?
		@inspections = @inspections.where("inspections.created_at < ?", params[:data2]) unless params[:data2].blank?
		@inspections = @inspections.joins(:equipment).where(equipment: {building_id: params[:building_id]}) unless params[:building_id].blank?
		@inspections = @inspections.where(approved: params[:approved_id]) unless params[:approved_id].blank?
		@inspections = @inspections.where(equipment_id: params[:equipment_id]) unless params[:equipment_id].blank?
	end
  
  def inspection_params
    params.require(:inspection).permit(:photo_url,:user_id,:equipment_id,:description,:group_id,:approved)
  end

  def answers_params
    params.require(:inspection).permit(answers_attributes[:is_ok])
  end

end

app/helpers/inspection_helper.rb
module InspectionHelper
end

app/views/inspections/_search.html.erb
<!--form_tag welcome_index_path, :method => 'get' do -->
<div class="container">
  <%= form_tag(inspections_path, method: "get") do %>
  <p> Predio:
    <%= building_array = @buildings.map {|building| [building.name, building.id]}
    building_array.unshift(['',''])
    select_tag(:building_id, options_for_select(building_array)) %>

   Data da inspeção: <input type="text" name="data1" placeholder="dd/mm/aa" size="10"> a <input type="text" name="data2" placeholder="dd/mm/aa" size="10">
  </p>
  <p>
    
  Estagiário:
      <% user_array = @users.map {|user| [user.name, user.id]} 
    user_array.unshift(['',''])%>
    <%= select_tag(:user_id, options_for_select(user_array)) %>

  Equipamento:
    <% equip_type_array = @equip_types.map {|equip_type| [equip_type.kind, equip_type.id]} 
    equip_type_array.unshift(['',''])%>
    <%= select_tag(:equip_type_id, options_for_select(equip_type_array)) %>


  </p>
    <%= submit_tag("Aplicar Filtros")%>
    <% end %>

</div>

<!-- end -->

app/views/inspections/_search_history.html.erb
<!--form_tag welcome_index_path, :method => 'get' do -->
<div class="container">
  <%= form_tag(inspections_index_history_path, method: "get") do %>
  <p> Predio:
    <%= building_array = @buildings.map {|building| [building.name, building.id]}
    building_array.unshift(['',''])
    select_tag(:building_id, options_for_select(building_array)) %>

   Data da inspeção: <input type="text" name="data1" placeholder="dd/mm/aa" size="10"> a <input type="text" name="data2" placeholder="dd/mm/aa" size="10">
  </p>
  <p>

  Estagiário:
      <% user_array = @users.map {|user| [user.name, user.id]}
    user_array.unshift(['',''])%>
    <%= select_tag(:user_id, options_for_select(user_array)) %>

  Equipamento:
    <% equip_type_array = @equip_types.map {|equip_type| [equip_type.kind, equip_type.id]}
    equip_type_array.unshift(['',''])%>
    <%= select_tag(:equip_type_id, options_for_select(equip_type_array)) %>


  </p>
    <%= submit_tag("Aplicar Filtros")%>
    <% end %>

</div>

<!-- end -->

app/views/inspections/_showInspection.erb
<table class="table">
    <tr>
        <th>ID</th>
        <td><%= @inspection.id%></td>
    </tr>
    <tr>
        <th>Grupo</th>
        <td><%= @inspection.group.try(:name)%></td>
    </tr>
    <tr>
        <th>Tipo do Ítem</th>
        <td><%= @inspection.equipment.equip_type.kind%></td>
    </tr>
    <tr>
        <th>Localização</th>
        <td><%= @inspection.equipment.building.name%></td>
    </tr>
    <tr>
        <th>Data da Inspeção</th>
        <td><%= @inspection.created_at%></td>
    </tr>
    <tr>
        <th>Inspetor</th>
        <td><%= @inspection.user.name%></td>
    </tr>
    <tr>
        <th>Descrição</th>
        <td><%= @inspection.description%></td>
    </tr>
    <tr>
        <th>Aprovado?</th>
        <td> <% if (@inspection.sent ==1)
                    %><p class="text-muted">Enviado</p><% else
                if (@inspection.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (@inspection.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (@inspection.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                end
                %></td>
    </tr>
</table>



<h3>Checklist</h3>

<% if (@inspection.equipment.is_there)  %>
<table class="table">
    <% if @answers.size == 0 %>
      Nenhuma pergunta foi respondida.
    <% end %>
    <% @answers.each do |answer| %>
        <tr>
            <td>
                <% if !answer.checklist_item.nil? %>
                  <%= answer.checklist_item.question %>
                  <br/>                                 
                <%  else %>
                  !PERGUNTA REMOVIDA!
                <% end %>
            </td>
            <td>
                <% if (answer.is_ok == 0)
                        %><p class="text-muted">Sim</p><% end
                    if (answer.is_ok == 1)
                        %><p class="text-muted">Não</p><% end
                    if (answer.is_ok == 2)
                        %><p class="text-muted">Não se aplica</p><%
                    end
                %>
            </td>
        </tr>
        <tr>
          <td colspan="2">
           <% if !answer.comment.nil? %>
                    <%= answer.comment%>
                  <% else %>
                    Nenhum comentário.
                  <% end %>   
                  <br/>
           <% answer.upload.each do |upload| %>
            <%= image_tag upload.photo.url %>
          <% end %>
          </td>
        </tr>
    <% end else %>
    <tr>Ítem de Inspeção não existe</tr>
    <% end %>
</table>

<div class="container">
  <table>
    <tr>
      <% if (@inspection.approved == 0) then %>
      <% if (current_user.kind == "admin") %>
      <td>
        <%= link_to 'Aprovar', { action: :validate, id: @inspection.id },  method: :validate,  :onclick => "return confirm('Certeza que deseja aprovar a inspeção?')", class: "btn btn-success"%>
      </td>
      <td>
        <%= link_to 'Reprovar', { action: :disapprove, id: @inspection.id },  method: :disapprove,  :onclick => "return confirm('Certeza que deseja reprovar a inspeção?')", class: "btn btn-danger" %>
      </td>
      <% else %>
        Apenas Adminstradores podem aprovar ou reprovar inspeções!
      <% end %>
      <% end %>

    </tr>
  </table>
</div>

app/views/inspections/disapprove.html.erb
<h1>Inspection#disapprove</h1>
<p>Find me in app/views/inspection/disapprove.html.erb</p>

app/views/inspections/edit.html.erb
<h1>Checklist</h1>
<hr>

<%= form_for @inspection, :html => {:multipart => :true } do |f| %>

<%= f.label :group_id, "Grupo Da Inspeção"%>
<%= f.collection_select :group_id, Group.all, :id, :name %>
<hr>
<% @questions.each do |id, question, q| %>

  <%= label_tag question, question %>
  <%= select('answers', id, @answertypes, :selected => @answer_data.where(checklist_item_id: id).first.try(:is_ok)) %>

  <%= label_tag "foto" ,"Escolha fotos para esta pergunta" %>
  <%= file_field :photos, id, :multiple => true %>

  <%= label_tag "comment", "Comentário" %>
  <%= text_area_tag "comment_" + id.to_s, @answer_data.where(checklist_item_id: id).first.try(:comment) %>

<hr>

<% end %>
<br/>
<%= f.submit "Salvar", :class => "btn default-button"%>

<% end %>

app/views/inspections/index.html.erb
<div class="search">
  <%= render :partial => 'search' %>
</div>

<i><%= link_to "Nova Inspeção", new_inspection_path %></i>

<table class="table table-striped table-hover">
    <tr>
        <th></th>
        <th>Grupo</th>
        <th>Equipamento</th>
        <th>Localização</th>
        <th>Data da Inspeção</th>
        <th>Estagiário</th>
        <th>Aprovado</th>
        <th></th>
        <th></th>
    </tr>
    <% @inspections.each do |insp| %>
        <tr>
            <td>
               <%= insp.id %>
            </td>
            <td>
               <%= insp.group.try(:name) %>
            </td>
            <td>
                <%= insp.equipment.name %> (<%= insp.equipment.equip_type.kind %>)
            </td>
            <td>
               <%= insp.equipment.building.name %>
            </td>
            <td>
               <%= insp.created_at %>
            </td>
            <td>
                <%= insp.user.name %>
            </td>
            <td>
                <% if (insp.sent == 1)
                    %><p class="text-muted">Enviado</p><% else
                if (insp.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (insp.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (insp.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                end
                %>
            </td>
            <td>
                    <%= link_to "Visualizar", insp  %>

            </td>
            <td>
              <%= link_to "Checklist", edit_inspection_path(:id => insp.id) %>
            </td>
        </tr>
    <% end -%>
</table>

app/views/inspections/index_history.html.erb
<div class="search">
  <%= render :partial => 'search_history' %>
</div>

<td><i><%= link_to "Nova Inspeção", new_inspection_path %></i>

<table class="table table-striped table-hover">
    <tr>
        <th></th>
        <th>Equipamento</th>
        <th>Localização</th>
        <th>Data da Inspeção</th>
        <th>Estagiário</th>
        <th>Aprovado</th>
        <th></th>
    </tr>
    <% @inspections.each do |insp| %>
        <tr>
            <td>
               <%= insp.id %>
            </td>
            <td>
                <%= insp.equipment.equip_type.kind %>
            </td>
            <td>
               <%= insp.equipment.building.name %>
            </td>
            <td>
               <%= insp.created_at %>
            </td>
            <td>
                <%= insp.user.name %>
            </td>
            <td>
                <% 
                if (insp.sent == 1)
                    %><p class="text-muted">Enviado</p><% else
                if (insp.approved == 0)
                    %><p class="text-muted">Pendente</p><% end
                if (insp.approved == 1)
                    %><p class="text-muted">Aprovado</p><% end
                if (insp.approved == 2)
                    %><p class="text-muted">Reprovado</p><% end
                end
                %>
            </td>
            <td>
                    <%= link_to "Visualizar", insp  %>

            </td>
        </tr>
    <% end -%>
</table>

app/views/inspections/new.html.erb
<b>Nova Inspeção</b>

<%= nested_form_for @inspection, :html => {:multipart => true} do |f| %>
	<br>
  <%= f.label :description, "Descrição" %>
  <%= f.text_field :description %>

  <%= f.label :equipment_id, "Ítem de Inspeção" %>
  <%= f.select(:equipment_id, options_for_select(@equipments, @equipment)) %>
        
  <%= f.label :group_id, "Grupo Da Inspeção"%>
  <%= f.collection_select :group_id, Group.all, :id, :name %>      

  <%= f.label :photo_url, "Escolha uma foto geral para a inspeção (se aplicável)" %>
  <%= f.file_field :photo_url %>

  <%= f.hidden_field 'user_id', :value => current_user.id %>
  <%= f.hidden_field 'approved', :value => 0 %>
  <br/>
  <%= f.submit "Salvar" %>
  
<%end%>

app/views/inspections/show.html.erb
<h2>Visualização de Inspeção</h2>

<%= render :partial => 'showInspection' %>

<br>
<div class="container">
  <img src="<%=  @inspection_url %>" class="img-rounded">
</div>

app/views/inspections/validate.html.erb
<h1>Inspection#validate</h1>
<p>Find me in app/views/inspection/validate.html.erb</p>