config/routes.rb
Hera::Application.routes.draw do
 
  devise_for :users, controllers: {users: "users"}
  
  devise_scope :users do
    get 'users/login' => 'devise/sessions#new'
    get 'users/logout' => 'devise/sessions#destroy'
  end
  
  resources :web_services_posts
  get "web_services/web_post" => "web_services_post#web_post"

  resources :web_services_gets
  get "web_services/get_checklist" => "web_services_get#get_checklist"
  get "web_services/get_building_name" => "web_services_get#get_building_name"

  get "equipment/disapprove"
  get "equipment/validate"
  get "inspections/disapprove"
  resources :web_servicess
  get "web_services/teste_mobile" => "web_services#teste_mobile"
  get "web_services/get_building_png" => "web_services#get_building_png"
  get "web_services/get_usp_png" => "web_services#get_usp_png"
  get "web_services/get_num_pav" => "web_services#get_num_pav"
  get "web_services/get_usp_map_info" => "web_services#get_usp_map_info"
  get "web_services/get_id_by_coordinate" => "web_services#get_id_by_coordinate"
  get "web_services/get_building_info" => "web_services#get_building_info"
  get "web_services/get_gml_by_code" => "web_services#get_gml_by_code"

  
  resources :equipment
  get "inspections/index_history"
  get "inspections/validate"
  resources :inspections
  
  resources :groups
  
  resources :buildings
  
  resources :user
  
  resources :equip_types
  
  get "gerenciamento/index"
  

  root 'gerenciamento#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :inspection
	belongs_to :checklist_item
  
  has_many :upload
end

app/models/building.rb
class Building < ActiveRecord::Base
	has_many :equipment

	validates :idAtlas, uniqueness: true, presence: true
end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
	belongs_to :equip_type
	has_many :answers

	validates :question, presence: true
	#validates :question, uniqueness: true
end

app/models/equip_type.rb
class EquipType < ActiveRecord::Base
	self.inheritance_column = nil
	has_many :equipment
	has_many :checklist_items
  
  accepts_nested_attributes_for :checklist_items, allow_destroy: true

	validates :kind, presence: true
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	has_many :inspections
	belongs_to :equip_type
	belongs_to :building
  
	validates :is_there, :inclusion => {:in => [true, false]}
  
  
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :inspections
  
  def index
    
  end
  
  def new
    
  end
  
  def create
    
  end
  
  def edit
    
  end
  
  def update
    
  end
end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  belongs_to :group
	belongs_to :user
	belongs_to :equipment
	has_many :answers

	mount_uploader :photo_url, PictureUploader
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_attached_file :photo
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  
  belongs_to :answer
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	self.inheritance_column = nil
	has_many :inspections

	validates :nusp, uniqueness: true
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
  end
  
  def show
    @group = Group.find(params[:id])
    @inspections = Inspection.where('group_id = ' + params[:id]).order("created_at DESC")
  end
  
  def new
    @group = Group.new
  end
  
  def create
    group = Group.new
    group.update_attributes(group_params)
    group.save
    redirect_to groups_path
  end
  
  def edit
    @group = Group.find_or_create_by_id(params[:id])
  end
  
  def update
    group = Group.find params[:id]
    group.update_attributes(group_params)
    group.save
    redirect_to groups_path
  end
  
  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    @inspections = Inspection.all
    @equipTypes = EquipType.all
    @users = User.all
    @users = @users.where("name like ?", "%#{params[:search]}%") unless params[:search].blank?
    @users = @users.where("kind = ?", params[:user_type]) unless params[:user_type].blank?
  end

  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find params[:id]
    @roles = [["Administrador/Aprovador","admin"],["Normal","normal"]]
    @role = @user.kind
    
    if (@role.nil?) 
      @role = "normal"
    end
  end
  
  def update
    user = User.find params[:id]
    user.update_attributes(userdata_params)
    user.save
    redirect_to user_path(params[:id])
  end
  
  def userdata_params
    params.require(:user).permit(:name,:nusp,:cpf,:kind)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/building_helper.rb
module BuildingHelper
end

app/helpers/checklist_item_helper.rb
module ChecklistItemHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/gerenciamento_helper.rb
module GerenciamentoHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/inspection_helper.rb
module InspectionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/web_services_helper.rb
module WebServicesHelper
end

app/views/layouts/_main_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top main-nav">
  <div class="navbar-inner mainnav">
    <div class="container-fluid">
      <%= image_tag "header_logo.png", class: "logo" %>
      <a href="<%= root_path %>" class="brand">
        legal
      </a>

    </div>
  </div>
</div>

<% if user_signed_in? -%>	
<div class="row-fluid">
    <div class="navbar">
      <div class="navbar-inner">
        <a class="brand" href="/">Gerenciamento</a>
        <ul class="nav">
          <li class="<%= "active" if @status == "all" %>">
            <%= link_to "Grupos de Inspeções", groups_path%>
          </li>
          <li class="<%= "active" if @status == "all" %>">
            <%= link_to "Ítem de Inspeção", equipment_index_path%>
          </li>
          
          <li class="<%= "active" if @status == "Não Analisado" %>">
            <%= link_to "Inspeções Pendentes", inspections_path%>
          </li>
          <li class="<%= "active" if @status == "Analisado" %>">
            <%= link_to "Inspeções Antigas", inspections_index_history_path%>
          </li>
          <li class="<%= "active" if @status == "all" %>">
            <%= link_to "Tipos de Item", equip_types_path%>
          </li>
          <li class="<%= "active" if @status == "all" %>">
            <%= link_to "Prédios", buildings_path%>
          </li>
          <li class="<%= "active" if @status == "Aceito" %>">
            <%= link_to "Usuários", user_index_path%>
          </li>
          
              <li>
                 <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
              </li>
        </ul>
      </div>
    </div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labsoft</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
</head>
<body>
  <%= javascript_include_tag 'rails' %>
  <%= javascript_include_tag 'jquery-1.11.0.min' %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render "layouts/main_nav" %>
  <%= yield %>

</body>
</html>